### ISSUE TITLE
New member

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#14]
I put in a new member on alpha (Fred Flintstone) but he does not appear on the membership list nor CMS membership history.

**Comment by mikebattye** [comment]
The reason is that I was over-zealous in my response to your requirement that passwords are not made visible - I removed all the password boxes! However, you do need a password box when creating a brand new user as without a password it cannot be done! (internally it complained that there was no password but, due to another big, I was ignoring this error!).
I will fix this in the next version BUT you can create new members using the registration feature as a work around on the current version.

**Comment by asimshah** [comment]
This should now be working as required.
