### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#15]
When I go to login and register at first it does not give the registration box. You have to cancel and then go through the process again before the box comes up. (Windows7/IE11)

**Comment by mikebattye** [comment]
Actually it is refreshing the page that works.

**Comment by asimshah** [comment]
So far I have not been able to reproduce this

**Comment by asimshah** [comment]
Please close this if it is not an issue.

**Comment by asimshah** [comment]
Ok, I am closing it!
