### ISSUE TITLE
Internal page links

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#17]
Am I correct in thinking that an internal page link has to the full url (eg http://dwh.test.webframe.co.uk/page/11)?

**Comment by asimshah** [comment]
Quite the reverse! In the example, the url should be page/11. You need full urls only when leaving the site.

**Comment by mikebattye** [comment]
I'll check it again this evening. I may have been adding a / at the beginning.


Regards,Mike
Sent from my S5 phone

-------- Original message --------
