### ISSUE TITLE
mail history links do not always show the mail content

### ISSUE THREAD

**Issue by asimshah** [asimshah/webframe-issues#22]
The most likely reason is that on paging, the handling of the click event on the email address is lost. Use of the datatable plug-in probably needs some re-work.

**Comment by mikebattye** [comment]
Any progress on this yet? Struggling to check email flow properly as links 'mostly' do not work

**Comment by asimshah** [comment]
I haven’t been working on it! I’d rather assumed that you had lost interest in the whole thing as I had heard nothing for such a long time!

 

I’ll start having a look at it this afternoon…
