### ISSUE TITLE
User profile (not critical)

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#24]
Hadn't noticed this before as was mainly using as Admin but should the user profile also have a logout option. Some people like to logout before closing the browser.

**Comment by asimshah** [comment]
I am not sure why you think it should be in the user profile. On the site, it is up to you to add a logout link  in a page panel and/or a menu (and manage access so that such a link is only available to those that have logged in). The link url needs to be /logout

**Comment by mikebattye** [comment]
There is a logout on the Admin home page. Of course I’ll put one on the other home page menus if necessary.

**Comment by asimshah** [comment]
Assuming you agree that this is not an issue, please close this

**Comment by asimshah** [comment]
Ok, I am closing it!
