### ISSUE TITLE
Upload file (Store)

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#28]
Slightly confusing when you upload file in Store - it does not give a clear confirmation that the upload has been successful. Instead it stays in this state until you close the box. 

![file upload](https://cloud.githubusercontent.com/assets/11847651/18834351/50c86e56-83ed-11e6-8592-7ba833fa4578.PNG)

**Comment by asimshah** [comment]
Fixed in the next version.

**Comment by asimshah** [comment]
Test is now upgraded

**Comment by asimshah** [comment]
Please test and close if possible
