### ISSUE TITLE
Accessing features

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#3]
I have tried page modification (edit) and accessed site design (though not attempted to change any CSS yet) but can't see how to access page creation or storage management. Am I missing something obvious?

>Features:

>1.       Site design using css
>2.       Page creation/modification using in-browser editing.
>3.       Storage management - folder creation only  for the time being (i.e. no access control stuff)

**Comment by asimshah** [comment]
I assume you can now do this, so I am closing this issue.
