### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#30]
Not sure how this will work when mail is enabled but at present there is no confirmation that password reset has been successful nor does the system log you in to the site after reset.

**Comment by asimshah** [comment]
I agree that is less than ideal. There are some issues about how to do the right thing. Can we leave it for now, or will it be too problematic?

**Comment by asimshah** [comment]
So ... I have made a change that means that on successful password reset, the user is logged into the site and taken to his/her home page.
This change is in the next version.

**Comment by asimshah** [comment]
dwhnew.test.webframe.co.uk now updated.
