### ISSUE TITLE
Layout Editor

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#32]
Don't know whether you've noticed this but selecting Cancel in the LESS editor doesn't take you back to the Editor screen. You have to click Layout on the top menu.

**Comment by asimshah** [comment]
Actually the cancel button is redundant so I have got rid of it.
This change is in the next version

**Comment by asimshah** [comment]
Test is now upgraded

**Comment by asimshah** [comment]
please close, if possible
