### ISSUE TITLE
A liquid layout can lose Admistrator link

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#9]
The black bar and Administrator link do not follow the layout of the site panel eg when this is made liquid. Probably a very complex reason for this and it may not be worth changing, but I point it out for the sake of completeness. 

![capture3](https://cloud.githubusercontent.com/assets/11847651/8476157/739942d4-20b6-11e5-805e-20dd1490a447.JPG)

**Comment by asimshah** [comment]
What do you think should happen given that a minimum width is required to allow the editor to function?

**Comment by asimshah** [comment]
latest releases has a large number of changes to help make the site naturally more responsive. Nevertheless the html content needs to written from a responsiveness perspective.
Particular care must be taken with, for example:
* Use of images
* use of tables
* use of explicit heights and widths
